### ISSUE TITLE
Error executing the command: yarn start:dev

### ISSUE THREAD

**Issue by AstroCorp** [mikro-orm/nestjs-example-app#1]
### Error:

`[Nest] 29103   - 2019-11-27 12:39:45   [ExceptionHandler] Metadata for entity BaseEntity not found +1ms
ValidationError: Metadata for entity BaseEntity not found`

**Comment by B4nan** [comment]
Fixed, base entities should not be part of `MikroOrmModule.forFeature()` as that is used to register repositories (and base entities have none).

Also updated dependencies and added support for CLI.
