### ISSUE TITLE
MikroORM failed to connect to database mikro-orm-nest-ts on mysql://root@127.0.0.1:3307

### ISSUE THREAD

**Issue by 7Z0nE** [mikro-orm/nestjs-example-app#17]
I cloned the repo then ran:

    yarn install`
    docker-compose up -d`
    yarn start:dev`

Outputs:

    [+] Running 1/0
     ⠿ Container mysql  Recreated                                                                                           0.1s
    Attaching to mysql
    mysql  | 2021-11-26 10:18:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.36-1debian10 started.
    mysql  | 2021-11-26 10:18:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
    mysql  | 2021-11-26 10:18:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.36-1debian10 started.
    mysql  | 2021-11-26 10:18:03+00:00 [Note] [Entrypoint]: Initializing database files
    mysql  | 2021-11-26T10:18:03.512913Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
    mysql  | 2021-11-26T10:18:03.702512Z 0 [Warning] InnoDB: New log files created, LSN=45790
    mysql  | 2021-11-26T10:18:03.742351Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
    mysql  | 2021-11-26T10:18:03.755362Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 24040116-4ea2-11ec-a56e-0242ac130402.
    mysql  | 2021-11-26T10:18:03.758786Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
    mysql  | 2021-11-26T10:18:04.226619Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
    mysql  | 2021-11-26T10:18:04.226639Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
    mysql  | 2021-11-26T10:18:04.226960Z 0 [Warning] CA certificate ca.pem is self signed.
    mysql  | 2021-11-26T10:18:04.437062Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
    mysql  | 2021-11-26 10:18:07+00:00 [Note] [Entrypoint]: Database files initialized
    mysql  | 2021-11-26 10:18:07+00:00 [Note] [Entrypoint]: Starting temporary server
    mysql  | 2021-11-26 10:18:07+00:00 [Note] [Entrypoint]: Waiting for server startup
    mysql  | 2021-11-26T10:18:07.840998Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
    mysql  | 2021-11-26T10:18:07.841876Z 0 [Note] mysqld (mysqld 5.7.36) starting as process 77 ...
    mysql  | 2021-11-26T10:18:07.844114Z 0 [Note] InnoDB: PUNCH HOLE support available
    mysql  | 2021-11-26T10:18:07.844148Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
    mysql  | 2021-11-26T10:18:07.844150Z 0 [Note] InnoDB: Uses event mutexes
    mysql  | 2021-11-26T10:18:07.844153Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
    mysql  | 2021-11-26T10:18:07.844156Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
    mysql  | 2021-11-26T10:18:07.844159Z 0 [Note] InnoDB: Using Linux native AIO
    mysql  | 2021-11-26T10:18:07.844332Z 0 [Note] InnoDB: Number of pools: 1
    mysql  | 2021-11-26T10:18:07.844525Z 0 [Note] InnoDB: Using CPU crc32 instructions
    mysql  | 2021-11-26T10:18:07.845801Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
    mysql  | 2021-11-26T10:18:07.850237Z 0 [Note] InnoDB: Completed initialization of buffer pool
    mysql  | 2021-11-26T10:18:07.851616Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
    mysql  | 2021-11-26T10:18:07.871218Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
    mysql  | 2021-11-26T10:18:07.881870Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
    mysql  | 2021-11-26T10:18:07.881937Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
    mysql  | 2021-11-26T10:18:07.899654Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
    mysql  | 2021-11-26T10:18:07.900533Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
    mysql  | 2021-11-26T10:18:07.900552Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
    mysql  | 2021-11-26T10:18:07.901044Z 0 [Note] InnoDB: Waiting for purge to start
    mysql  | 2021-11-26T10:18:07.951244Z 0 [Note] InnoDB: 5.7.36 started; log sequence number 2749723
    mysql  | 2021-11-26T10:18:07.951465Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
    mysql  | 2021-11-26T10:18:07.951803Z 0 [Note] Plugin 'FEDERATED' is disabled.
    mysql  | 2021-11-26T10:18:07.953204Z 0 [Note] InnoDB: Buffer pool(s) load completed at 211126 10:18:07
    mysql  | 2021-11-26T10:18:07.959073Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
    mysql  | 2021-11-26T10:18:07.959111Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
    mysql  | 2021-11-26T10:18:07.959119Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
    mysql  | 2021-11-26T10:18:07.959124Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
    mysql  | 2021-11-26T10:18:07.960222Z 0 [Warning] CA certificate ca.pem is self signed.
    mysql  | 2021-11-26T10:18:07.960303Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
    mysql  | 2021-11-26T10:18:07.965992Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
    mysql  | 2021-11-26T10:18:07.977949Z 0 [Note] Event Scheduler: Loaded 0 events
    mysql  | 2021-11-26T10:18:07.978424Z 0 [Note] mysqld: ready for connections.
    mysql  | Version: '5.7.36'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
    mysql  | 2021-11-26 10:18:08+00:00 [Note] [Entrypoint]: Temporary server started.
    mysql  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
    mysql  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
    mysql  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
    mysql  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
    mysql  | 
    mysql  | 2021-11-26 10:18:10+00:00 [Note] [Entrypoint]: Stopping temporary server
    mysql  | 2021-11-26T10:18:10.392735Z 0 [Note] Giving 0 client threads a chance to die gracefully
    mysql  | 2021-11-26T10:18:10.392848Z 0 [Note] Shutting down slave threads
    mysql  | 2021-11-26T10:18:10.392861Z 0 [Note] Forcefully disconnecting 0 remaining clients
    mysql  | 2021-11-26T10:18:10.392870Z 0 [Note] Event Scheduler: Purging the queue. 0 events
    mysql  | 2021-11-26T10:18:10.392971Z 0 [Note] Binlog end
    mysql  | 2021-11-26T10:18:10.393581Z 0 [Note] Shutting down plugin 'ngram'
    mysql  | 2021-11-26T10:18:10.393600Z 0 [Note] Shutting down plugin 'partition'
    mysql  | 2021-11-26T10:18:10.393603Z 0 [Note] Shutting down plugin 'BLACKHOLE'
    mysql  | 2021-11-26T10:18:10.393609Z 0 [Note] Shutting down plugin 'ARCHIVE'
    mysql  | 2021-11-26T10:18:10.393613Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
    mysql  | 2021-11-26T10:18:10.393648Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
    mysql  | 2021-11-26T10:18:10.393655Z 0 [Note] Shutting down plugin 'MyISAM'
    mysql  | 2021-11-26T10:18:10.393665Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
    mysql  | 2021-11-26T10:18:10.393670Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
    mysql  | 2021-11-26T10:18:10.393673Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
    mysql  | 2021-11-26T10:18:10.393676Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
    mysql  | 2021-11-26T10:18:10.393680Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
    mysql  | 2021-11-26T10:18:10.393683Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
    mysql  | 2021-11-26T10:18:10.393686Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
    mysql  | 2021-11-26T10:18:10.393690Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
    mysql  | 2021-11-26T10:18:10.393693Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
    mysql  | 2021-11-26T10:18:10.393696Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
    mysql  | 2021-11-26T10:18:10.393699Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
    mysql  | 2021-11-26T10:18:10.393703Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
    mysql  | 2021-11-26T10:18:10.393708Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
    mysql  | 2021-11-26T10:18:10.393713Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
    mysql  | 2021-11-26T10:18:10.393718Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
    mysql  | 2021-11-26T10:18:10.393723Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
    mysql  | 2021-11-26T10:18:10.393726Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
    mysql  | 2021-11-26T10:18:10.393733Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
    mysql  | 2021-11-26T10:18:10.393736Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
    mysql  | 2021-11-26T10:18:10.393740Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
    mysql  | 2021-11-26T10:18:10.393743Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
    mysql  | 2021-11-26T10:18:10.393746Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
    mysql  | 2021-11-26T10:18:10.393749Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
    mysql  | 2021-11-26T10:18:10.393752Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
    mysql  | 2021-11-26T10:18:10.393754Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
    mysql  | 2021-11-26T10:18:10.393758Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
    mysql  | 2021-11-26T10:18:10.393761Z 0 [Note] Shutting down plugin 'INNODB_CMP'
    mysql  | 2021-11-26T10:18:10.393764Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
    mysql  | 2021-11-26T10:18:10.393768Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
    mysql  | 2021-11-26T10:18:10.393771Z 0 [Note] Shutting down plugin 'INNODB_TRX'
    mysql  | 2021-11-26T10:18:10.393775Z 0 [Note] Shutting down plugin 'InnoDB'
    mysql  | 2021-11-26T10:18:10.393846Z 0 [Note] InnoDB: FTS optimize thread exiting.
    mysql  | 2021-11-26T10:18:10.393983Z 0 [Note] InnoDB: Starting shutdown...
    mysql  | 2021-11-26T10:18:10.494304Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
    mysql  | 2021-11-26T10:18:10.494706Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 211126 10:18:10
    mysql  | 2021-11-26T10:18:11.919319Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12659811
    mysql  | 2021-11-26T10:18:11.922397Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
    mysql  | 2021-11-26T10:18:11.922428Z 0 [Note] Shutting down plugin 'MEMORY'
    mysql  | 2021-11-26T10:18:11.922436Z 0 [Note] Shutting down plugin 'CSV'
    mysql  | 2021-11-26T10:18:11.922443Z 0 [Note] Shutting down plugin 'sha256_password'
    mysql  | 2021-11-26T10:18:11.922448Z 0 [Note] Shutting down plugin 'mysql_native_password'
    mysql  | 2021-11-26T10:18:11.922630Z 0 [Note] Shutting down plugin 'binlog'
    mysql  | 2021-11-26T10:18:11.925154Z 0 [Note] mysqld: Shutdown complete
    mysql  | 
    mysql  | 2021-11-26 10:18:12+00:00 [Note] [Entrypoint]: Temporary server stopped
    mysql  | 
    mysql  | 2021-11-26 10:18:12+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
    mysql  | 
    mysql  | 2021-11-26T10:18:12.572287Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
    mysql  | 2021-11-26T10:18:12.573006Z 0 [Note] mysqld (mysqld 5.7.36) starting as process 1 ...
    mysql  | 2021-11-26T10:18:12.574858Z 0 [Note] InnoDB: PUNCH HOLE support available
    mysql  | 2021-11-26T10:18:12.574876Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
    mysql  | 2021-11-26T10:18:12.574879Z 0 [Note] InnoDB: Uses event mutexes
    mysql  | 2021-11-26T10:18:12.574881Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
    mysql  | 2021-11-26T10:18:12.574884Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
    mysql  | 2021-11-26T10:18:12.574886Z 0 [Note] InnoDB: Using Linux native AIO
    mysql  | 2021-11-26T10:18:12.575012Z 0 [Note] InnoDB: Number of pools: 1
    mysql  | 2021-11-26T10:18:12.575059Z 0 [Note] InnoDB: Using CPU crc32 instructions
    mysql  | 2021-11-26T10:18:12.576082Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
    mysql  | 2021-11-26T10:18:12.580143Z 0 [Note] InnoDB: Completed initialization of buffer pool
    mysql  | 2021-11-26T10:18:12.581585Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
    mysql  | 2021-11-26T10:18:12.592908Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
    mysql  | 2021-11-26T10:18:12.608268Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
    mysql  | 2021-11-26T10:18:12.608339Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
    mysql  | 2021-11-26T10:18:12.626275Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
    mysql  | 2021-11-26T10:18:12.627176Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
    mysql  | 2021-11-26T10:18:12.627189Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
    mysql  | 2021-11-26T10:18:12.627596Z 0 [Note] InnoDB: Waiting for purge to start
    mysql  | 2021-11-26T10:18:12.677919Z 0 [Note] InnoDB: 5.7.36 started; log sequence number 12659811
    mysql  | 2021-11-26T10:18:12.678448Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
    mysql  | 2021-11-26T10:18:12.678812Z 0 [Note] Plugin 'FEDERATED' is disabled.
    mysql  | 2021-11-26T10:18:12.681187Z 0 [Note] InnoDB: Buffer pool(s) load completed at 211126 10:18:12
    mysql  | 2021-11-26T10:18:12.684562Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
    mysql  | 2021-11-26T10:18:12.684591Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
    mysql  | 2021-11-26T10:18:12.684597Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
    mysql  | 2021-11-26T10:18:12.684601Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
    mysql  | 2021-11-26T10:18:12.685390Z 0 [Warning] CA certificate ca.pem is self signed.
    mysql  | 2021-11-26T10:18:12.685446Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
    mysql  | 2021-11-26T10:18:12.686171Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
    mysql  | 2021-11-26T10:18:12.686236Z 0 [Note] IPv6 is available.
    mysql  | 2021-11-26T10:18:12.686253Z 0 [Note]   - '::' resolves to '::';
    mysql  | 2021-11-26T10:18:12.686274Z 0 [Note] Server socket created on IP: '::'.
    mysql  | 2021-11-26T10:18:12.690894Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
    mysql  | 2021-11-26T10:18:12.702727Z 0 [Note] Event Scheduler: Loaded 0 events
    mysql  | 2021-11-26T10:18:12.703337Z 0 [Note] mysqld: ready for connections.
    mysql  | Version: '5.7.36'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
    mysql  | 2021-11-26T10:19:11.736873Z 2 [Note] Unknown database 'mikro-orm-nest-ts'

--

    yarn run v1.22.17
    $ nodemon
    [nodemon] 2.0.4
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching path(s): src/**/*
    [nodemon] watching extensions: ts
    [nodemon] starting `ts-node -r tsconfig-paths/register src/main.ts`
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [NestFactory] Starting Nest application...
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [InstanceLoader] OrmModule dependencies initialized +19ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [InstanceLoader] MikroOrmModule dependencies initialized +0ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [InstanceLoader] AppModule dependencies initialized +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [discovery] ORM entity discovery started, using ReflectMetadataProvider
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [discovery] - processing entity Author
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [discovery] - processing entity Book
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [discovery] - processing entity BookTag
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [discovery] - processing entity Publisher
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [discovery] - processing entity BaseEntity
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [discovery] - entity discovery finished, found 6 entities, took 20 ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [MikroORM] [info] MikroORM failed to connect to database mikro-orm-nest-ts on mysql://root@127.0.0.1:3307
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [InstanceLoader] MikroOrmCoreModule dependencies initialized +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [InstanceLoader] MikroOrmModule dependencies initialized +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [InstanceLoader] AuthorModule dependencies initialized +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [InstanceLoader] BookModule dependencies initialized +0ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RoutesResolver] AppController {}: +6ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {, GET} route +2ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RoutesResolver] AuthorController {/author}: +0ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/author, GET} route +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/author/:id, GET} route +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/author, POST} route +0ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/author/:id, PUT} route +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RoutesResolver] BookController {/book}: +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/book, GET} route +0ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/book/:id, GET} route +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/book, POST} route +1ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [RouterExplorer] Mapped {/book/:id, PUT} route +0ms
    [Nest] 360637   - 11/26/2021, 11:19:11 AM   [NestApplication] Nest application successfully started +3ms

To my understanding the orm should successfully connect to the database.

Hope this can be resolved, best Fred.

**Comment by B4nan** [comment]
You need to create the database, as you can see from the very last line in the mysql log:

```
mysql  | 2021-11-26T10:19:11.736873Z 2 [Note] Unknown database 'mikro-orm-nest-ts'
```

You can use the CLI to do it:

```
// this will both create the database and the schema (tables)
npx mikro-orm schema:create -r
```
